FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /src

COPY . .

RUN dotnet restore ZooManager.API/ZooManager.API.csproj

RUN dotnet tool install -g dotnet-ef --version 7.0.14
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "ZooManager.Infrastructure", "--startup-project", "ZooManager.API"]
