services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - zoo-net
    restart: always

  api:
    build:
      context: .
      dockerfile: ZooManager.API/Dockerfile
    container_name: zoo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - zoo-net

  ef-migrator:
    build:
      context: .
      dockerfile: Dockerfile.ef-migrator
    depends_on:
      - sqlserver
    networks:
      - zoo-net





networks:
  zoo-net:
    driver: bridge



